default_stages: [pre-push]

repos:
  - repo: local
    hooks:
      - id: quality-gates
        name: quality-gates
        entry: make quality
        language: system
        pass_filenames: false
        stages: [pre-push]
